language: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.14      
os:
  - linux

install:
  # Install Anaconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - source activate test-environment
  - conda install --yes numpy=$NUMPY pytest conda-build anaconda-client setuptools cython cmake
  - conda config --set anaconda_upload no
  - export VERSION=`date +%Y.%m`	
  - conda build recipe/ --numpy=$NUMPY --python=$TRAVIS_PYTHON_VERSION 
  - conda install --channel /home/travis/miniconda/envs/test-environment/conda-bld/ i23-seg --offline --override-channels

after_success:
  - chmod +x recipe/conda_upload.sh
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash recipe/conda_upload.sh
  
script:
  - python tests/test.py
